---

- name: apt update
  apt: update_cache=yes cache_valid_time=3600
  register: apt_result|success
  retries: 3
  delay: 1
  become: yes
  become_method: sudo
  ignore_errors: yes

- name: install base packages
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - git
    - build-essential
    - apt-transport-https
    - python3-dev
    - python3-pip
    - libmysqlclient-dev
  become: yes
  become_method: sudo

- name: system upgrade
  apt:
    upgrade: full
    force: yes
  become: yes
  become_method: sudo

- name: make app group
  action: group name=ezctf state=present
  become: yes
  become_method: sudo

- name: make app user
  user:
    name: ctfapp
    group: ezctf
  become: yes
  become_method: sudo

