- name: Install mysql packages 
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - mysql-server
    - python-mysqldb
  become: yes
  become_method: sudo

- name: Start the mysql services
  service: name=mysql state=started enabled=yes
  become: yes
  become_method: sudo

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=0600

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
  become: yes
  become_method: sudo

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
   - localhost

- name: remove the test database
  mysql_db: name=test state=absent

- name: remove the .my.cnf from the home dir of the provisioner
  file:
    path: ~/.my.cnf
    state: absent
  become: yes
  become_method: sudo

- name: copy over db_setup.py for initial db build
  copy:
    src: files/db_setup.py
    dest: /opt/ezctf/linted_ctf
    owner: ctfapp
    group: ezctf
  become: yes
  become_method: sudo

- name: provision db for initial usage
  shell: source /opt/venvs/ezctf/bin/activate && python /opt/ezctf/linted_ctf/db_setup.py

- name: remove db build artifact
  file:
    path: /opt/ezctf/linted_ctf/db_setup.py
    state: absent
  become: yes
  become_method: sudo

#local db setup
- name: create db user for our app
  mysql_user: name={{app_dbuser}} password={{app_dbpass}}
              priv="*{{app_db}}*:ALL" state=present host="localhost"
  when: mysql == "local"
